# require in Vagrantgile
app:
  box: "centos/7"
  hosts:
    - hostname: "api-01"
      lips:
        - "10.10.10.10"
  provisions:
    - "/tmp/provision/app_provision.sh"
  volumes:
    - cookbooks:/tmp/cookbooks
    - roles:/tmp/roles
    - nodes:/tmp/nodes
    - provision:/tmp/provision
mysql:
  box: "centos/7"
  hosts:
    - hostname: "mysql-01"
      lips:
        - "10.10.10.200"
  provisions:
    - "/tmp/provision/mysql_provision.sh"
  volumes:
    - cookbooks:/tmp/cookbooks
    - roles:/tmp/roles
    - nodes:/tmp/nodes
    - provision:/tmp/provision
redis:
  box: "centos/7"
  hosts:
    - hostname: "redis-01.adroute.jp"
      lips:
        - "10.10.10.250"
  provisions:
    - "/tmp/provision/redis_provision.sh"
  volumes:
    - cookbooks:/tmp/cookbooks
    - roles:/tmp/roles
    - nodes:/tmp/nodes
    - provision:/tmp/provision
